"""Pedagogical state detection and Gagné event selection.

Pure-Python logic — no LLM calls. Ported from frontend mockTutor.ts.
"""

from __future__ import annotations

import json
import logging

from domain import FaceSignal, PedagogicalState, TutoringSession
from infrastructure.knowledge_base import get_topic

logger = logging.getLogger(__name__)


# Maps pedagogical state to recommended Gagné intervention events.
INTERVENTION_MAP: dict[str, dict[str, int | None]] = {
    "confusion":     {"primary": 4, "secondary": 5},
    "frustration":   {"primary": 5, "secondary": 6},
    "demotivation":  {"primary": 1, "secondary": 2},
    "fatigue":       {"primary": None, "secondary": None},
    "engaged":       {"primary": None, "secondary": None},
    "neutral":       {"primary": None, "secondary": None},
}

# Maps Gagné event IDs to the knowledge-base sections needed.
GAGNE_TO_SECTION: dict[int, list[str] | None] = {
    1: ["aplicaciones_reales", "mnemotecnia"],
    2: None,  # objectives — generated by LLM, no external content
    3: ["prerequisitos", "concepto"],
    4: ["concepto", "ejemplos"],
    5: ["ejemplos", "contraejemplos"],
    6: ["ejercicios"],
    7: None,  # feedback — LLM evaluates student response
    8: ["ejercicios"],
    9: ["aplicaciones_reales"],
}


def detect_state(
    student_message: str,
    face_signal: FaceSignal | None,
    turns_in_current_event: int,
    intentos: int,
) -> PedagogicalState:
    """Fuse text and facial signals into a pedagogical state."""
    msg = student_message.lower()
    trimmed = student_message.strip()

    text_signals: dict[str, bool] = {
        "frustration": any(
            p in msg
            for p in ["no puedo", "muy difícil", "no sirvo", "imposible", "ugh", "me rendí", "para qué"]
        ),
        "confusion": any(
            p in msg
            for p in ["no entiendo", "no comprendo", "cómo", "por qué", "no sé", "perdido", "confundido", "???"]
        ),
        "fatigue": turns_in_current_event > 8 or intentos > 3,
        "demotivation": (
            len(trimmed) < 10
            or trimmed.lower() in ("ok", "si", "sí", "no", "...", "aja")
        ),
        "engaged": len(student_message) > 40 and "?" in student_message,
    }

    face_map: dict[str, str | None] = {
        "confused": "confusion",
        "frustrated": "frustration",
        "sleepy": "fatigue",
        "engaged": "engaged",
        "neutral": None,
    }
    face_pedagogical: str | None = None
    if face_signal and face_signal.confidence > 0.65:
        face_pedagogical = face_map.get(face_signal.state)

    # Priority order
    priority = ["frustration", "confusion", "fatigue", "demotivation", "engaged"]
    detected: str = next((k for k in priority if text_signals.get(k)), "neutral")

    confidence: float
    sources: list[str]

    if face_pedagogical and face_pedagogical == detected:
        confidence = min(0.95, (face_signal.confidence if face_signal else 0.7) + 0.15)
        sources = ["text", "face"]
    elif face_pedagogical and face_pedagogical != detected:
        confidence = 0.60
        sources = ["text"]
    elif detected != "neutral":
        confidence = 0.75
        sources = ["text"]
    else:
        confidence = 0.50
        sources = ["text"]

    return PedagogicalState(
        state=detected,
        confidence=confidence,
        sources=sources,
        recommended_event=None,
    )


def select_gagne_event(session: TutoringSession, ped: PedagogicalState) -> int:
    """Select the next Gagné event based on session state and pedagogical signals."""
    entry = session.topic_actual
    current = session.gagne_event_actual
    seq = entry.gagne_sequence
    intervention = INTERVENTION_MAP.get(ped.state, INTERVENTION_MAP["neutral"])

    # Fatigue → micro-achievement via practice
    if ped.state == "fatigue" and 6 in seq:
        ped.recommended_event = 6
        return 6

    # Demotivation → recapture attention
    if ped.state == "demotivation" and 1 in seq and current != 1:
        ped.recommended_event = 1
        return 1

    # Specific intervention (confusion, frustration)
    primary = intervention["primary"]
    if primary is not None and primary in seq:
        target_idx = seq.index(primary)
        current_idx = seq.index(current) if current in seq else 0
        if target_idx >= max(0, current_idx - 2):
            ped.recommended_event = primary
            return primary

    # Engaged or neutral → advance in sequence
    if ped.state in ("engaged", "neutral") and session.turns_in_current_event >= 1:
        current_idx = seq.index(current) if current in seq else 0
        if current_idx < len(seq) - 1:
            next_event = seq[current_idx + 1]
            ped.recommended_event = next_event
            return next_event

    # Default: stay on current event
    ped.recommended_event = current
    return current


def load_topic_section(topic_id: str, gagne_event: int) -> dict:
    """Load relevant knowledge-base sections for a Gagné event.

    Returns a dict with ``topic_titulo``, optional ``prerequisitos``,
    and ``content`` (a subset of the topic's ``secciones``).
    """
    topic = get_topic(topic_id)
    if topic is None:
        return {"topic_titulo": topic_id, "content": None}

    sections_needed = GAGNE_TO_SECTION.get(gagne_event)

    if sections_needed is None:
        return {"topic_titulo": topic["titulo"], "content": None}

    secciones = topic["secciones"]
    content: dict = {}
    for key in sections_needed:
        if key == "prerequisitos":
            content["prerequisitos"] = topic.get("prerequisitos", [])
        elif key in secciones:
            content[key] = secciones[key]

    return {
        "topic_titulo": topic["titulo"],
        "prerequisitos": topic.get("prerequisitos", []),
        "content": content,
    }


def format_topic_section_for_prompt(section_data: dict) -> str:
    """Format the output of ``load_topic_section`` as human-readable text for a prompt."""
    content = section_data.get("content")
    if content is None:
        return f"Tema: {section_data['topic_titulo']}\n(Sin contenido de referencia para este evento.)"

    parts = [f"Tema: {section_data['topic_titulo']}"]

    if "concepto" in content:
        parts.append(f"Concepto: {content['concepto']}")

    if "ejemplos" in content:
        for i, ex in enumerate(content["ejemplos"], 1):
            if isinstance(ex, dict):
                parts.append(f"Ejemplo {i}: {ex.get('enunciado', '')} → {ex.get('solucion', '')}")
                if ex.get("paso_a_paso"):
                    parts.append(f"  Pasos: {' → '.join(ex['paso_a_paso'])}")
            else:
                parts.append(f"Ejemplo {i}: {ex}")

    if "contraejemplos" in content:
        parts.append(f"Contraejemplos: {', '.join(content['contraejemplos'])}")

    if "ejercicios" in content:
        for ej in content["ejercicios"]:
            if isinstance(ej, dict):
                parts.append(f"Ejercicio [{ej.get('nivel', '?')}]: {ej.get('enunciado', '')} → {ej.get('respuesta', '')}")

    if "aplicaciones_reales" in content:
        parts.append(f"Aplicaciones reales: {'; '.join(content['aplicaciones_reales'])}")

    if "mnemotecnia" in content:
        parts.append(f"Mnemotecnia: {content['mnemotecnia']}")

    if "prerequisitos" in content:
        parts.append(f"Prerequisitos: {', '.join(content['prerequisitos'])}")

    return "\n".join(parts)
